services:
  myblog_server:
    build: .
    image: myblog
    container_name: myblog_server
    ports:
      - "80:8080"
    environment:
      MYSQL_HOST: mysql_server
      MYSQL_DB: myblog_db
      MYSQL_USER: root
      MYSQL_PWD: nevertellyou
    volumes:
      - myblog_data:/opt/myblog/data
    depends_on:
      mysql_server:
        condition: service_healthy

  mysql_server:
    image: mysql:8.0
    container_name: mysql_server
    volumes:
      - C:/opt:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nevertellyou
      MYSQL_DATABASE: myblog_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  myblog_data:
